# Generated by Django 3.2.7 on 2023-02-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_bot', '0003_auto_20230131_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_model',
            options={'verbose_name': 'Appointment List'},
        ),
    ]
